steps:
  # Build Backend Image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "australia-southeast1-docker.pkg.dev/$PROJECT_ID/meccanico/backend:$COMMIT_SHA",
        "./backend",
      ]

images:
  - "australia-southeast1-docker.pkg.dev/$PROJECT_ID/meccanico/backend:$COMMIT_SHA"
