name: Deploy Backend (Prod)

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_PROD }}
  REGION: australia-southeast1
  SERVICE_NAME: meccanico-backend-prod
  JOB_NAME: meccanico-admin-bootstrap-prod
  REPOSITORY: meccanico-backend # Name of the artifact registry repository or image name

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER_PROD }}
          service_account: ${{ secrets.GCP_GHA_SA_EMAIL_PROD }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build and Push Container
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}:${{ github.sha }} .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}:${{ github.sha }}
          env_vars: |
            NODE_ENV=production

      - name: Run admin bootstrap job
        run: |
          gcloud run jobs execute ${{ env.JOB_NAME }} \
            --region ${{ env.REGION }} \
            --project ${{ env.PROJECT_ID }} \
            --wait
